# Generated by Django 6.1 on 2026-09-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_pic',
            new_name='small_profile_pic',
        ),
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='goes_on_staff_page',
            field=models.BooleanField(default=False, verbose_name='Goes on staff page?'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='headshot',
            field=models.ImageField(blank=True, height_field=500, upload_to='headshots', verbose_name='Headshot', width_field=500),
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Job Title'),
        ),
    ]
