# Generated by Django 6.1 on 2026-09-02 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_profile_pic', models.ImageField(blank=True, default='static/img/pfpDefault.png', upload_to='profilePics', verbose_name='Profile Picture')),
                ('headshot', models.ImageField(blank=True, upload_to='headshots', verbose_name='Headshot')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Description')),
                ('job_title', models.CharField(blank=True, max_length=50, verbose_name='Job Title')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='description',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='headshot',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='small_profile_pic',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='accounts.profile'),
            preserve_default=False,
        ),
    ]
