# Generated by Django 6.1 on 2026-09-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_remove_customuser_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='small_profile_pic',
            field=models.ImageField(blank=True, default='static/image/pfpDefault.png', upload_to='profilePics', verbose_name='Profile Picture'),
        ),
    ]
