# Generated by Django 6.1 on 2026-09-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_small_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='headshot',
            field=models.ImageField(blank=True, default='static/image/headshotDefault.png', upload_to='headshots', verbose_name='Headshot'),
        ),
    ]
